### ISSUE TITLE
Release CSW 2.0.2 ebRIM I15

### ISSUE THREAD

**Issue by bermud** [opengeospatial/cite#10]
Make avialable in OGC TE facility the CSW 2.0.2 ebRIM I15 test.

Status:
is in idea status

2 implementations are available
1. An OpenSource ebRIM implementation which is currently under revision by Intecs: http://www.buddata-open.org/. For details you can ask Maria (see cc).
2. An opensource implementation of a Bridge (http://code.google.com/p/transforming-inspire-discovery-vs-hma-collection-discovery/) sitting on top of the EUMETSAT ProductNavigator (PNs). This cannot be 100% conformant as it just maps the ebRIM I15 requests/responses to/from the PNs CSW 2.0.2 AP ISO Interface (which is a semantic subset of the ebRIM I15). The Interface URL´s can be found in the ctl UserForm.

**Comment by bermud** [comment]
@lorebiga, would you be interested in examining this  ebRIM test and maybe incorporate it to the current CAT 2.0?

**Comment by lorebiga** [comment]
@bermud, I'm not familiar with the spec, but could probably take a look. Where the candidate ETS?

**Comment by ghobona** [comment]
This issue has been overtaken by events.
