### ISSUE TITLE
Improve documentation about how to develop a test using testng

### ISSUE THREAD

**Issue by bermud** [opengeospatial/cite#31]
Continuing the steps from this page:
https://github.com/opengeospatial/cite/wiki/Conformance-Testing-with-TestNG

And, merging some information from here:
https://github.com/opengeospatial/teamengine/blob/master/src/site/markdown/testers.md

**Comment by rjmartell** [comment]
The first draft is complete. See https://github.com/opengeospatial/cite/wiki/Conformance-Testing-with-TestNG.

**Comment by rjmartell** [comment]
There are now two documents covering the use of TestNG

1. [Conformance Testing with TestNG, Part 1: Essentials](https://github.com/opengeospatial/cite/wiki/Conformance-Testing-with-TestNG-Part-1)
2. [[Conformance Testing with TestNG, Part 2: Cookbook](https://github.com/opengeospatial/cite/wiki/Conformance-Testing-with-TestNG-Part-2)

**Comment by rjmartell** [comment]
These documents were also added to the TEAM Engine site (v4.5).
