### ISSUE TITLE
Prepare TE 4.4 for OSGeo-Live DVD

### ISSUE THREAD

**Issue by bermud** [opengeospatial/cite#32]
Build cycle for version 9.5 of the OSGeo-Live [1] DVD/USB/VM which will be released in March 2016, ready for several special events, including FOSS4G-NA, FOSSGIS (Salzburg, Austria), among others. 

Key Milestones 
11 Jan 2016 All new applications installed, most old applications updated 
01 Feb 2016 Feature Freeze (all apps updated) 
15 Feb 2016 User Acceptance Test (all apps installed and working) 
21 Mar 2016 Final ISO sent to printers 

[1] http://live.osgeo.org

**Comment by bermud** [comment]
Better to work on this after testbed 12 where we will have some funding and resources dedicated to creating a virtual appliance

**Comment by dstenger** [comment]
@bermud This issue is probably outdated?
