### ISSUE TITLE
Wrong "version" parameter in GetCapabilities requests

### ISSUE THREAD

**Issue by matthias-mueller** [opengeospatial/cite#40]
The GetCapabilities requests on the [wiki site of reference implemetations](
https://github.com/opengeospatial/cite/wiki/Reference-Implementations) use a wrong version parameter. For GetCapabilities it is "accptVersions" (OGC 06-121r6, Table 3), not "version":

http://demo.pycsw.org/cite/csw?service=CSW&acceptVersions=2.0.2&request=GetCapabilities

(Since this is a very common pitfall, most implementations handle this glitch gracefully.)

**Comment by bermud** [comment]
@matthias-mueller
Thank you for reporting. You are correct.  
CSW 2.0.2 (OGC 07-006r1) depends on Web Services common (OGC 05-008). Web Services Common says that the getCapabilities should use AcceptVersions. I have update the URLs.
