### ISSUE TITLE
Test new production

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/cite#44]
New production is currently reachable via http://cite.opengeospatial.org/te3/.

This version shall be tested extensively before moving it to production URL.

Please execute following steps:
* Use user `ogctest`.
* For each test suite execute one test run with reference implementation [1].
  * Document URL to test result.
  * Document if reference implementation passes tests.
  * Document any unexpected behaviour.

[1] https://github.com/opengeospatial/cite/wiki/Reference-Implementations

**Comment by keshav-nangare** [comment]
Production3  Test result:

|ETS Name |Reference URL|Result|Exception|Result Link|
|------------|----------------|-------|-----------|-----------|
Catalogue Service - Web (CSW) 2.0.2 | http://demo.pycsw.org/cite/csw?service=CSW&acceptVersions=2.0.2&request=GetCapabilities | Passed |   | http://cite.opengeospatial.org/te3/viewOldSessionLog.jsp?session=s0147
Catalogue Service - Web (CSW) 3.0.0 | http://demo.pycsw.org/cite/csw?service=CSW&version=3.0.0&request=GetCapabilities | Failed | Few tests are failed with following error:getCapabilitiesBySection:               org.opengis.cite.validation.SchematronValidator.validate(Ljavax/xml/transform/Source;)Ljavax/xml/transform/dom/DOMResult; | http://cite.opengeospatial.org/te3/viewOldSessionLog.jsp?session=s0148
GeoPackage 1.0 | https://demo.luciad.com/GeoPackageData/states10.gpkg | Skipped | All tests are Skipped | http://cite.opengeospatial.org/te3/viewSessionLog.jsp?session=s0152
Geography Markup Language (GML) 3.2.1 | http://cite.deegree.org/deegree-webservices-3.4.0/services/gml321?service=WFS&request=GetFeature&Version=2.0.0&typenames=app:Autos | Passed |   | http://cite.opengeospatial.org/te3/viewSessionLog.jsp?session=s0153
OGC KML 2.2 | Default-https://developers.google.com/kml/documentation/KML_Samples.kml | Passed |   | http://cite.opengeospatial.org/te3/viewSessionLog.jsp?session=s0154
Sensor Observation Service (SOS) 1.0.0 | URL is not present |   |   |  
Sensor Observation Service (SOS) 2.0 | http://sensorweb.demo.52north.org/52n-sos-webapp/service?service=SOS&request=GetCapabilities&AcceptVersions=2.0.0 | Failed | Few tests are failed | http://cite.opengeospatial.org/te3/viewOldSessionLog.jsp?session=s0155
Sensor Planning Service (SPS) 1.0 | URL is not present |   |   |  
Sensor Planning Service (SPS) 2.0 | http://sensorweb.demo.52north.org/52n-sps-2.0/sps?request=GetCapabilities |   |   |  
SensorThings API 1.0 | URL is not present |   |   |  
Simple Feature Access - SQL (SFS) 1.1 | URL is not present |   |   |  
Simple Feature Access - SQL (SFS) 1.2.1 | URL is not present |   |   |  
Web Coverage Service (WCS) 1.0.0 | URL is not present |   |   |  
Web Coverage Service (WCS) 1.1.1 | URL is not present |   |   |  
Web Coverage Service (WCS) 2.0.1 | http://ows.eox.at/cite/mapserver?service=wcs&version=2.0.1&request=getcapabilities |   |   |  
Web Feature Service (WFS) 1.0.0 | http://cite.deegree.org/deegree-webservices-3.4.0/services/wfs100?service=WFS&request=GetCapabilities |   |   |  
Web Feature Service (WFS) 1.1.0 | http://cite.deegree.org/deegree-webservices-3.4.0/services/wfs110?service=WFS&request=GetCapabilities |   |   |  
Web Feature Service (WFS) 2.0 | http://cite.deegree.org/deegree-webservices-3.4.0/services/wfs200?service=WFS&request=GetCapabilities |   |   |  
Web Map Service (WMS) 1.1.1 | http://cite.deegree.org/deegree-webservices-3.4.0/services/wms111?service=WMS&request=GetCapabilities |   |   |  
Web Map Service (WMS) 1.3.0 | http://cite.deegree.org/deegree-webservices-3.4.0/services/wms130?service=WMS&request=GetCapabilities |   |   |  
Web Map Service (WMS) - Client 1.3.0 |   |   |   |  
Web Map Tile Service (WMTS) 1.0.0 | http://cite.deegree.org/deegree-webservices-3.4.0/services/wmts100?service=WMTS&request=GetCapabilities |   |   |
