### ISSUE TITLE
Test WFS services of USGS

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/cite#45]
Please run tests for all WFS services linked here https://carto.nationalmap.gov/wfs.

All services provide the WFS 2.0 interface. Thus, just this test suite must be used.
Please test with production [1] and beta [2] environments.

Document the results here a please provide a link to the test results (you can create a new user for test executions and send the password to me).

[1] http://cite.opengeospatial.org/teamengine/
[2] http://cite.opengeospatial.org/te2/

**Comment by keshav-nangare** [comment]
WFS services with capability document link:

- geonames (MapServer) : https://carto.nationalmap.gov/wfs/services/geonames/MapServer/WFSServer?request=GetCapabilities&service=WFS
- govunits (MapServer) : https://carto.nationalmap.gov/wfs/services/govunits/MapServer/WFSServer?request=GetCapabilities&service=WFS
- selectable_polygons (MapServer) : https://carto.nationalmap.gov/wfs/services/selectable_polygons/MapServer/WFSServer?request=GetCapabilities&service=WFS
- structures (MapServer) : https://carto.nationalmap.gov/wfs/services/structures/MapServer/WFSServer?request=GetCapabilities&service=WFS
- transportation (MapServer) : https://carto.nationalmap.gov/wfs/services/transportation/MapServer/WFSServer?request=GetCapabilities&service=WFS

**Comment by keshav-nangare** [comment]
Following are the results:

<table>
  <thead>
  <tr>
    <th rowspan="2">Services</th>
    <th rowspan="2">URL</th>
    <th colspan="2">Results</th>
	<th colspan="2">Session</th>
  </tr>
  <tr>
    <th>Production</th>
    <th>Beta</th>
	<th>Production</th>
    <th>Beta</th>
  </tr>
  </thead>
  <tr>
  <td>geonames (MapServer)</td>	
  <td>https://carto.nationalmap.gov/wfs/services/geonames/MapServer/WFSServer?request=GetCapabilities&service=WFS</td>	
  <td>Failed</td>	
  <td>Failed</td>	
  <td>http://cite.opengeospatial.org/teamengine/viewSessionLog.jsp?session=s0001</td>	
  <td>http://cite.opengeospatial.org/te2/viewSessionLog.jsp?session=s0001</td>
  </tr>
  <tr>
	<td>govunits (MapServer)</td>	
	<td>https://carto.nationalmap.gov/wfs/services/govunits/MapServer/WFSServer?request=GetCapabilities&service=WFS</td>	
	<td>Failed</td>	
	<td>Failed</td>	
	<td>http://cite.opengeospatial.org/teamengine/viewSessionLog.jsp?session=s0002</td>	
	<td>http://cite.opengeospatial.org/te2/viewSessionLog.jsp?session=s0002<td>
  </tr>
  <tr>
	<td>selectable_polygons (MapServer)</td>	
	<td>https://carto.nationalmap.gov/wfs/services/selectable_polygons/MapServer/WFSServer?request=GetCapabilities&service=WFS</td>	
	<td>Failed</td>	<td>Failed</td>	<td>http://cite.opengeospatial.org/teamengine/viewSessionLog.jsp?session=s0003</td>	
	<td>http://cite.opengeospatial.org/te2/viewSessionLog.jsp?session=s0003</td>
  </tr>	
  <tr>
	<td>structures (MapServer)</td>	
	<td>https://carto.nationalmap.gov/wfs/services/structures/MapServer/WFSServer?request=GetCapabilities&service=WFS</td>	
	<td>Failed</td>	
	<td>Failed</td>	
	<td>http://cite.opengeospatial.org/teamengine/viewSessionLog.jsp?session=s0004</td>	
	<td>http://cite.opengeospatial.org/te2/viewSessionLog.jsp?session=s0004</td>
  </tr>
  <tr>	
	<td>transportation (MapServer)</td>	
	<td>https://carto.nationalmap.gov/wfs/services/transportation/MapServer/WFSServer?request=GetCapabilities&service=WFS</td>	
	<td>Failed</td>	
	<td>Failed</td>	
	<td>http://cite.opengeospatial.org/teamengine/viewSessionLog.jsp?session=s0005</td>	
	<td>http://cite.opengeospatial.org/te2/viewSessionLog.jsp?session=s0005</td>
  </tr>
</table>

**Comment by dstenger** [comment]
@keshav-nangare 
Can you please test the same services with WFS 1.1 test suite and post the results here (same pattern as before)?

**Comment by keshav-nangare** [comment]
Results for WFS 1.1 test suite:


<table>
  <thead>
  <tr>
    <th rowspan="2">Services</th>
    <th rowspan="2">URL</th>
    <th colspan="2">Results</th>
	<th colspan="2">Session</th>
  </tr>
  <tr>
    <th>Production</th>
    <th>Beta</th>
	<th>Production</th>
    <th>Beta</th>
  </tr>
  </thead>
  <tr>
  <td>geonames (MapServer)</td>	
  <td>https://carto.nationalmap.gov/wfs/services/geonames/MapServer/WFSServer?request=GetCapabilities&service=WFS&version=1.1.0</td>	
  <td>Failed</td>	
  <td>Failed</td>	
  <td>http://cite.opengeospatial.org/teamengine/viewSessionLog.jsp?session=s0006</td>	
  <td>http://cite.opengeospatial.org/te2/viewSessionLog.jsp?session=s0006</td>
  </tr>
  <tr>
	<td>govunits (MapServer)</td>	
	<td>https://carto.nationalmap.gov/wfs/services/govunits/MapServer/WFSServer?request=GetCapabilities&service=WFS&version=1.1.0</td>	
	<td>Failed</td>	
	<td>Failed</td>	
	<td>http://cite.opengeospatial.org/teamengine/viewSessionLog.jsp?session=s0007</td>	
	<td>http://cite.opengeospatial.org/te2/viewSessionLog.jsp?session=s0007<td>
  </tr>
  <tr>
	<td>selectable_polygons (MapServer)</td>	
	<td>https://carto.nationalmap.gov/wfs/services/selectable_polygons/MapServer/WFSServer?request=GetCapabilities&service=WFS&version=1.1.0</td>	
	<td>Failed</td>	
	<td>Failed</td>	
	<td>http://cite.opengeospatial.org/teamengine/viewSessionLog.jsp?session=s0008</td>	
	<td>http://cite.opengeospatial.org/te2/viewSessionLog.jsp?session=s0008</td>
  </tr>	
  <tr>
	<td>structures (MapServer)</td>	
	<td>https://carto.nationalmap.gov/wfs/services/structures/MapServer/WFSServer?request=GetCapabilities&service=WFS&version=1.1.0</td>	
	<td>Failed</td>	
	<td>Failed</td>	
	<td>http://cite.opengeospatial.org/teamengine/viewSessionLog.jsp?session=s0009</td>	
	<td>http://cite.opengeospatial.org/te2/viewSessionLog.jsp?session=s0009</td>
  </tr>
  <tr>	
	<td>transportation (MapServer)</td>	
	<td>https://carto.nationalmap.gov/wfs/services/transportation/MapServer/WFSServer?request=GetCapabilities&service=WFS&version=1.1.0</td>	
	<td>Failed</td>	
	<td>Failed</td>	
	<td>http://cite.opengeospatial.org/teamengine/viewSessionLog.jsp?session=s0010</td>	
	<td>http://cite.opengeospatial.org/te2/viewSessionLog.jsp?session=s0010</td>
  </tr>
</table>
