### ISSUE TITLE
Push image of test suite to Docker hub

### ISSUE THREAD

**Issue by brawer** [opengeospatial/cite#46]
Could you push an image of the test suite to [Docker hub](https://hub.docker.com/) or a similar container registry? Then, people could run the tests against their own implementation just with `docker run`, without building the test suite and without having to deal with Java toolchains.

**Comment by dstenger** [comment]
Thank you for the request.

We are already pushing single test suites to Docker Hub and are planning to extend this activity.

Please check out https://hub.docker.com/u/ogccite.

**Comment by dstenger** [comment]
Is there a particular test suite you are interested in?

**Comment by brawer** [comment]
Yes, the [WFS 3.0 Conformance Test Suite](https://github.com/opengeospatial/ets-wfs30). I’ve written a custom server and would love to run the test suite against my implementation.

**Comment by dstenger** [comment]
We are working on this in https://github.com/opengeospatial/ets-wfs30/issues/51.
So, Image will be available via Docker Hub soon.

**Comment by dstenger** [comment]
@brawer 
WFS 3.0 test suite is available via Docker Hub, now.
Please see https://hub.docker.com/r/ogccite/ets-wfs30.
