### ISSUE TITLE
Create repository for GeoTIFF 1.1

### ISSUE THREAD

**Issue by bermud** [opengeospatial/cite#48]
GeoTIFF 1.1 is now finalized and ready for submission to the TC for a ballot as an OGC standard, it’s time to consider the testing of this well-known imagery/elevation data format in the OGC.
 
The standard is available under OGC github at https://github.com/opengeospatial/geotiff/
 
From the Annex A / ATS, Chuck developed a Detailed Test Suite available at https://github.com/opengeospatial/geotiff/tree/master/GeoTIFF_Standard which should facilitate implementation of ETS.
 
In addition to this, Even Rouault (on OSGEO GDAL side) updated the development branch of the libgeotiff and GDAL for geotiff, already ready for GeoTIFF 1.1 (in addition the existing GeoTIFF 1.0) and provided some testing sample files that might be of interest to you. See below information.

**Comment by dstenger** [comment]
Proposed name for repository: `ets-geotiff11`

**Comment by lgoltz** [comment]
Repository exists: https://github.com/opengeospatial/ets-geotiff11
