### ISSUE TITLE
Create list of all test suites using dependency geomatics-geotk

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/cite#52]
Background: New release shall be created containing following pull request: https://github.com/opengeospatial/geomatics-geotk/pulls

**Comment by keshav-nangare** [comment]
@dstenger @ghobona 

The following test suites contain geomatics-geotk dependency:
1. ets-gml32
2. ets-cat30
3. ets-gpkg12-nsg

**Comment by dstenger** [comment]
Can you please create an issue in all three test suites to update geomatics-geotk to version 1.15?

**Comment by dstenger** [comment]
Please also add this issue in WFS 2.0 tracker.
