### ISSUE TITLE
Create 'Cleanup dependencies' issues for all TestNG based test suites

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/cite#54]
See https://github.com/opengeospatial/ets-wfs20/issues/172 as an example.

Please create a check list containing all considered test suites, create a new issue in each test suite and link the corresponding issues in the check list.

Please also consider TEAM Engine itself.

**Comment by keshav-nangare** [comment]
Following test suites and teamengine to be updated:

- [ ] ets-cat30
- [ ] ets-cat20-dgiwg10
- [ ] ets-wfs20-dgiwg
- [ ] ets-wms13-dgiwg
- [ ] ets-gmljpx20
- [ ] ets-gpkg10
- [ ] ets-gpkg12
- [ ] ets-geotiff11
- [ ] ets-gpkg12-nsg
- [ ] ets-wfs20-nsg10
- [ ] ets-wms13-nsg
- [ ] ets-wmts10-nsg10
- [ ] ets-kml22
- [ ] ets-kml2
- [ ] ets-omxml20
- [ ] ets-swecommon20
- [ ] ets-sensorml20
- [ ] ets-sta10
- [ ] ets-cdb10
- [ ] teamengine
