### ISSUE TITLE
Test new production (November 2020)

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/cite#55]
New production is currently reachable via http://cite.opengeospatial.org/te3/.

This version shall be tested extensively before moving it to production URL.

Please execute following steps:
* Use user `ogctest`.
* For each test suite execute one test run with reference implementation [1].
  * Document URL to test result.
  * Document if reference implementation passes tests.
  * Document any unexpected behavior.

Hints:
* See last issue of full testing of new production: #44

[1] https://github.com/opengeospatial/cite/wiki/Reference-Implementations

**Comment by keshav-nangare** [comment]
Please find results in pdf:

[Testing of new production (November 2020).xlsx - Sheet1.pdf](https://github.com/opengeospatial/cite/files/5558893/Testing.of.new.production.November.2020.xlsx.-.Sheet1.pdf)

**Comment by dstenger** [comment]
@keshav-nangare 
Can you please check current production (/teamengine) for following test suites?
* SOS 2.0
* SensorThings API
* WFS 1.0

Is the behavior the same as on /te3?

**Comment by keshav-nangare** [comment]
@dstenger 

1. The new HTML report generation fails on production and /te3 but generates on the beta environment for the SOS 2.0 test suite.
2. The behavior of the SensorThings API, WFS 1.1 and WFS 1.0 test suite is the same on production as on /te3.

**Comment by dstenger** [comment]
2021-02-22 meeting: @dstenger is installing release on te2 (copy of Production tomcat) this week so that Keshav can test it.
