### ISSUE TITLE
REST API with technical response requires template in all test suites

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/cite#56]
Please see https://github.com/opengeospatial/teamengine/issues/397.

There shall be an issue be created for all test suites installed on Beta.

**Comment by dstenger** [comment]
@keshav-nangare Can you please create a list of test suites where those changes are already existing?

**Comment by keshav-nangare** [comment]
@dstenger 

The technical information related to the test suite such as title, version, endpoint, etscode will be available in XML/JSON without adding any template i.e at the [endpoint](https://cite.opengeospatial.org/te2/rest/suites).
The information related to specific test suite execution will require the template to get an XML/JSON response. e.g [endpoint](https://cite.opengeospatial.org/te2/rest/suites/ogcapi-features-1.0/).

**Comment by keshav-nangare** [comment]
Following test suites to be updated with a template:
- [ ] ets-cat30
- [ ] ets-gml32
- [ ] ets-gpkg10
- [ ] ets-gpkg12
- [ ] ets-kml22
- [ ] ets-kml2
- [ ] ets-owc10
- [ ] ets-sensorml20
- [ ] ets-sos20
- [ ] ets-sta10
- [ ] ets-wcs11
- [ ] ets-wcs20
- [ ] ets-wfs10
- [ ] ets-wfs20
- [ ] ets-wms11
- [ ] ets-wms13
- [ ] ets-wmts10
- [ ] ets-omxml20
- [ ] ets-swecommon20
- [ ] ets-wfs20-dgiwg
- [ ] ets-wms13-dgiwg
- [ ] ets-wfs20-nsg
- [ ] ets-wmts10-nsg
- [ ] ets-gpkg12-nsg
- [ ] ets-wms13-nsg
- [ ] ets-ogcapi-features10
- [ ] ets-gmljpx20
- [ ] ets-cat20-dgiwg10
- [ ] ets-cdb10
- [ ] ets-geotiff11
