### ISSUE TITLE
Test new production (February 2021)

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/cite#57]
Environment: http://cite.opengeospatial.org/te3/

Please see https://github.com/opengeospatial/cite/issues/55.

**Comment by keshav-nangare** [comment]
Please find results in pdf:

[Testing_new_production_result.pdf](https://github.com/opengeospatial/cite/files/6044068/Testing_new_production_result_february.pdf)

**Comment by dstenger** [comment]
@keshav-nangare 
Can you please compare all results with "Different" results on te3 and te2 with current production (https://cite.opengeospatial.org/teamengine/)? te3 and current production should behave exactly the same.

**Comment by keshav-nangare** [comment]
@dstenger 

The current production and te3 have same behavior for the "Different" results test suites on te2.

**Comment by dstenger** [comment]
Behavior of "old" and "new" Production is the same.
TEAM Engine 5.4.1 can be moved to Production (after it has been installed on Beta for one month).
