### ISSUE TITLE
@keshav-nangare transition plan

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/cite#58]
@keshav-nangare to ensure that all code has been pushed to GitHub

- [x] ets-ogcapi-edr10
- [x] ets-ogcapi-features10
- [x] ..

For issues in progress, please add a comment to the original issue and cross link from this transition issue. Please identify the branch or pull request in the issue comment.

**Comment by keshav-nangare** [comment]
I have added changes for the following issues, their changes are pushed to the respective repo and branch name mentioned in the issue. 
1. https://github.com/opengeospatial/ets-wmts10/issues/27
2. https://github.com/opengeospatial/ets-ogcapi-features10/issues/18
3. https://github.com/opengeospatial/ets-ogcapi-features10/issues/19
4. https://github.com/opengeospatial/teamengine/issues/210
5. https://github.com/opengeospatial/teamengine/issues/32
6. https://github.com/opengeospatial/ets-wfs20/issues/30

**Comment by keshav-nangare** [comment]
I have added changes for `ets-ogcapi-edr10` for the following tests:
1. Abstract test 
2. Abstract test 
3. Abstract test 
4. Abstract test 
5. Abstract test 
6. Abstract test 
7. Abstract test 
8. Abstract test 
9. Abstract test 
10. Abstract test 
11. Abstract test 
12. Abstract test

**Comment by dstenger** [comment]
Add following sentence "This pull request is not finalized yet (in progress) and can be used as a basis for future work." to all PRs of https://github.com/opengeospatial/cite/issues/58#issuecomment-814907046.
