### ISSUE TITLE
CSW test data

### ISSUE THREAD

**Issue by mhogeweg** [opengeospatial/cite#59]
can someone remind me where to find the CSW 2.0.2 test data? and is this the same data as tested in CSW 3.0.0?

**Comment by dstenger** [comment]
@mhogeweg The CSW 2.0.2 test data can be downloaded here: https://cite.opengeospatial.org/teamengine/about/csw/2.0.2/site/

**Comment by mhogeweg** [comment]
thanks! do you know if anyone has converted these csw:Record data to 'regular' metadata (ISO/FGDC)?

**Comment by ghobona** [comment]
There's a **Best Practice** document for the FGDC CSDGM Application Profile for CSW 2.0 (0.0.12).

https://portal.ogc.org/files/?artifact_id=16936

**Comment by mhogeweg** [comment]
Thanks. I have never seen people submit csw:Record metadata to SDI catalogs, open data sites, clearinghouses, etc. People create and manage FGDC/ISO/INSPIRE/Gemini/SDSFIE-M/ANZLIC/... metadata to those catalogs. Catalogs then index that and pick the right fields for CSW API interactions from that (for example guided by that FGDC profile). Catalogs typically contain a broad mix of metadata standards and profiles. Just surprised that no one seems to have translated the test data (which are API responses, not metadata) to one of those metadata standards.
