### ISSUE TITLE
Towards an Executable Test Suite for CityGML 2.0

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/cite#60]
To help us identify a suitable CityGML 2.0 validator to use with TEAM Engine, we have created this GitHub Issue to capture some of the insight and lessons learnt as we review available open source libraries.

To start off with, here are the libraries we have come across:

* CityDoctor2, https://transfer.hft-stuttgart.de/gitlab/citydoctor/citydoctor2

* citygml4java, https://github.com/citygml4j/citygml4j

The review will be in two stages:

For each of the available libraries, here are the questions we have to answer:

* Can the library be easily built following the information that is on the documentation?

* Can the library be imported into an instance of TEAM Engine 5.5, running inside Tomcat 7 and running in a Java 1.8?

* Is the library being regularly maintained (i.e. with multiple contributors and several recent commits)?

Please note that this issue does not mean that CITE is proceeding to implement the Executable Test Suite. The research is to help us understand whether such an activity is feasible and could be justified.

**Comment by dstenger** [comment]
After reviewing the libraries listed above, the CITE team has agreed to implement the ETS using citygml4java.

**Comment by dstenger** [comment]
@arieslai to check the highest version of citygml4java supporting Java 8 and Tomcat 7.

**Comment by arieslai** [comment]
Checked with the latest version v2.12.2 and it is able to run with command in Java 8 and Tomcat 7:
mvn clean install -Dsource=8  docker:run -Pdocker
