### ISSUE TITLE
Test all test suites installed on Beta environment with TEAM Engine 6 (Java 17)

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/cite#66]
A GitHub issue shall be created for each test suite which needs to be adjusted (in the issue tracker of the target test suite).

Further findings shall be documented in this issue.

**Comment by dstenger** [comment]
Checklist of test suites which were already tested:

- [ ] Catalogue Service - Web (CSW) 	2.0.2 	1.18 	Final
- [x] Catalogue Service - Web (CSW) 	3.0.0 	1.4 	Final
- [x] CityGML 2.0 	2.0 	0.2 	Beta
- [ ] DGIWG Catalogue Service for the Web 2.0 (DGIWG CSW) 	1.0 	0.4 	Beta
- [x] DGIWG Web Feature Service (DGIWG WFS) 	2.0 	0.7 	Beta
- [ ] DGIWG Web Map Service (DGIWG WMS) 	2.1.0 	0.5 	Beta
- [x] GML in JPEG 2000 (GMLJP2) 	2.0 	1.2 	Final
- [x] GeoPackage 	1.0 	1.2 	Final
- [x] GeoPackage 	1.2 	1.1 	Final
- [x] GeoPose 1.0 	1.0 	1.0 	Final
- [x] GeoTiff 	1.1 	1.1 	Final
- [x] Geography Markup Language (GML) 	3.2 	1.31 	Final
- [x] IndoorGML 1.0 	1.0 	0.1 	Beta
- [x] NSG GeoPackage 1.1 Profile 	2.1 	0.7 	Beta
- [x] NSG WFS 2.0 Profile 	1.0 	0.6 	Beta
- [x] NSG WMS 1.3 Profile 	1.0 	0.5 	Beta
- [x] NSG WMTS 1.0 Profile 	1.0 	0.4 	Beta
- [x] OGC API - Environmental Data Retrieval 	1.0 	1.0 	Final
- [x] OGC API - Features 	1.0 	1.7 	Final
- [x] OGC API - Processes 	1.0 	1.1 	Final
- [ ] OGC API - Tiles 	1.0 	0.2 	Beta
- [ ] OGC CDB 	1.0 	1.1 	Final
- [x] OGC EO Dataset Metadata GeoJSON 	1.0 	0.2 	Beta
- [x] OGC GeoRSS Encoding Standard 	1.0 	1.0 	Final
- [x] OGC KML 	2.2 	1.15 	Final
- [x] OGC KML 2.x 	2.x 	0.5 	Beta
- [ ] OGC Web Service Security Client 	1.0 	0.6 	Beta
- [ ] OWS Context 	1.0 	0.2 	Beta
- [x] Observations and Measurements - XML Implementation (OMXML) 	2.0 	1.1 	Final
- [x] SWE Common Data Model Encoding Standard 	2.0 	1.1 	Final
- [ ] Sensor Model Language (SensorML) 	1.0.1 	1.0.1 	Final
- [x] Sensor Model Language (SensorML) 	2.0 	1.0 	Final
- [ ] Sensor Observation Service (SOS) 	1.0.0 	1.14 	Final
- [ ] Sensor Observation Service (SOS) 	2.0 	1.14 	Final
- [ ] Sensor Planning Service (SPS) 	2.0 	1.11 	Final
- [ ] SensorThings API 	1.0 	1.4 	Final
- [ ] Simple Feature Access - SQL (SFS) 	1.1 	1.8 	Final
- [ ] Simple Feature Access - SQL (SFS) 	1.2.1 	1.4 	Final
- [ ] Web Coverage Service (WCS) 	1.0.0 	1.17 	Final
- [ ] Web Coverage Service (WCS) 	1.1.1 	1.17 	Final
- [ ] Web Coverage Service (WCS) 	2.0.1 	1.20 	Final
- [ ] Web Feature Service (WFS) 	1.0.0 	1.13 	Final
- [x] Web Feature Service (WFS) 	1.1.0 	1.36 	Final
- [x] Web Feature Service (WFS) 	2.0 	1.40 	Final
- [ ] Web Map Service (WMS) 	1.1.1 	1.22 	Final
- [ ] Web Map Service (WMS) 	1.3.0 	1.31 	Final
- [ ] Web Map Service (WMS) - Client 	1.3.0 	1.6 	Final
- [ ] Web Map Tile Service (WMTS) 	1.0.0 	1.7 	Final
- [ ] Web Processing Service (WPS) 	2.0 	1.0 	Final
- [ ] Web Processing Service 1.0 	1.0 	0.8 	Beta

**Comment by dstenger** [comment]
Created issues for test suites:
- https://github.com/opengeospatial/ets-wfs20/issues/266
- https://github.com/opengeospatial/ets-ogcapi-processes10/issues/94
- https://github.com/opengeospatial/ets-ogcapi-features10/issues/235
- https://github.com/opengeospatial/ets-geotiff11/issues/43
- https://github.com/opengeospatial/ets-cat30/issues/55
- https://github.com/opengeospatial/ets-gml32/issues/78
- https://github.com/opengeospatial/ets-ogcapi-edr10/issues/122
- https://github.com/opengeospatial/ets-gpkg12-nsg/issues/62

Issues for libraries:
- https://github.com/opengeospatial/geomatics-geotk/issues/16

**Comment by mbrachman** [comment]
@jiann please pair with @dstenger on this task once you have completed the documentation for City GML

**Comment by dstenger** [comment]
Test environment: https://cite-dev-01.ogc.org/teamengine/

**Comment by dstenger** [comment]
Further issue created:
* https://github.com/opengeospatial/ets-citygml20/issues/34

**Comment by dstenger** [comment]
Reference implementations are listed [here](https://www.ogc.org/resources/certified-products/?display_opt=2).

**Comment by jiann** [comment]
| Name | Test INPUT | result |
|----------|----------|----------|
| Catalogue Service - Web (CSW) 2.0.2 1.18 Final   | http://demo.pycsw.org/cite/csw?service=CSW&version=2.0.2&request=GetCapabilities  | PASS   |
| DGIWG Catalogue Service for the Web 2.0 (DGIWG CSW) 1.0 0.4 Beta |  |  |
| DGIWG Web Feature Service (DGIWG WFS) 2.0 0.7 Beta | https://raw.githubusercontent.com/opengeospatial/ets-wfs20-dgiwg/master/src/test/resources/de/latlon/ets/wfs20/core/capabilities_wfs200.xml | Error in call to extension function {public java.lang.Object com.occamlab.te.TECore.callFunction(net.sf.saxon.expr.XPathContext,java.lang.String,java.lang.String,net.sf.saxon.om.NodeInfo) throws java.lang.Exception}: Exception in extension function net.sf.saxon.s9api.SaxonApiException: Error in call to extension function {public javax.xml.transform.Source de.latlon.ets.core.AbstractTestNGController.doTestRun(org.w3c.dom.Document) throws java.lang.Exception}: Exception in extension function java.lang.NoClassDefFoundError: Could not initialize class org.geotoolkit.referencing.crs.DefaultGeographicCRS  |
| DGIWG Web Map Service (DGIWG WMS) 2.1.0 0.5 Beta | https://raw.githubusercontent.com/opengeospatial/ets-wms13-dgiwg/master/src/test/resources/de/latlon/ets/wms13/core/capabilities_wms130.xml |  Error in call to extension function {public java.lang.Object com.occamlab.te.TECore.callFunction(net.sf.saxon.expr.XPathContext,java.lang.String,java.lang.String,net.sf.saxon.om.NodeInfo) throws java.lang.Exception}: Exception in extension function net.sf.saxon.s9api.SaxonApiException: Error in call to extension function {public static java.lang.String de.latlon.ets.wms13.core.util.interactive.InteractiveTestUtils.retrieveGetFeatureInfoRequest(java.lang.String)}: Exception in extension function java.lang.NoClassDefFoundError: javax/ws/rs/core/UriBuilder |
| GML in JPEG 2000 (GMLJP2) 2.0 1.2 Final | htttp://123.com  | Error in call to extension function {public java.lang.Object com.occamlab.te.TECore.callFunction(net.sf.saxon.expr.XPathContext,java.lang.String,java.lang.String,net.sf.saxon.om.NodeInfo) throws java.lang.Exception}: Exception in extension function net.sf.saxon.s9api.SaxonApiException: Error in call to extension function {public javax.xml.transform.Source org.opengis.cite.gmljpx20.TestNGController.doTestRun(org.w3c.dom.Document) throws java.lang.Exception}: Exception in extension function java.lang.NoClassDefFoundError: com/sun/jersey/spi/inject/Errors$Closure  |
| GeoPackage 1.0 1.2 Final | http://www.geopackage.org/data/simple_sewer_features.gpkg  | Error in call to extension function {public java.lang.Object com.occamlab.te.TECore.callFunction(net.sf.saxon.expr.XPathContext,java.lang.String,java.lang.String,net.sf.saxon.om.NodeInfo) throws java.lang.Exception}: Exception in extension function net.sf.saxon.s9api.SaxonApiException: Error in call to extension function {public javax.xml.transform.Source org.opengis.cite.gpkg10.TestNGController.doTestRun(org.w3c.dom.Document) throws java.lang.Exception}: Exception in extension function java.lang.NoClassDefFoundError: com/sun/jersey/spi/inject/Errors$Closure  |
| GeoPackage 1.2 1.1 Final | http://www.geopackage.org/data/simple_sewer_features.gpkg   |  Error in call to extension function {public java.lang.Object com.occamlab.te.TECore.callFunction(net.sf.saxon.expr.XPathContext,java.lang.String,java.lang.String,net.sf.saxon.om.NodeInfo) throws java.lang.Exception}: Exception in extension function net.sf.saxon.s9api.SaxonApiException: Error in call to extension function {public javax.xml.transform.Source org.opengis.cite.gpkg10.TestNGController.doTestRun(org.w3c.dom.Document) throws java.lang.Exception}: Exception in extension function java.lang.NoClassDefFoundError: com/sun/jersey/spi/inject/Errors$Closure |
| GeoPose 1.0 1.0 1.0 Final | file: {"position":{"lat":47.7,"lon":-122.3,"h":11.5},"angles":{"yaw":5.514,"pitch":-0.436,"roll":0.0}}  | Error in call to extension function {public java.lang.Object com.occamlab.te.TECore.callFunction(net.sf.saxon.expr.XPathContext,java.lang.String,java.lang.String,net.sf.saxon.om.NodeInfo) throws java.lang.Exception}: Exception in extension function net.sf.saxon.s9api.SaxonApiException: Error in call to extension function {public javax.xml.transform.Source org.opengis.cite.geopose10.TestNGController.doTestRun(org.w3c.dom.Document) throws java.lang.Exception}: Exception in extension function java.lang.NoClassDefFoundError: com/sun/jersey/core/util/FeaturesAndProperties  |
| IndoorGML 1.0 1.0 0.1 Beta | https://raw.githubusercontent.com/opengeospatial/ets-indoorgml10/master/src/test/resources/FJK-Haus_IndoorGML_withEXR-corrected_1_0_3.gml | Error in call to extension function {public java.lang.Object com.occamlab.te.TECore.callFunction(net.sf.saxon.expr.XPathContext,java.lang.String,java.lang.String,net.sf.saxon.om.NodeInfo) throws java.lang.Exception}: Exception in extension function net.sf.saxon.s9api.SaxonApiException: Error in call to extension function {public javax.xml.transform.Source org.opengis.cite.indoorgml10.TestNGController.doTestRun(org.w3c.dom.Document) throws java.lang.Exception}: Exception in extension function java.lang.NoClassDefFoundError: com/sun/jersey/spi/inject/Errors$Closure |
| NSG WFS 2.0 Profile 1.0 0.6 Beta | https://raw.githubusercontent.com/opengeospatial/ets-wfs20-nsg10/master/src/test/resources/capabilities-simple.xml | Error in call to extension function {public java.lang.Object com.occamlab.te.TECore.callFunction(net.sf.saxon.expr.XPathContext,java.lang.String,java.lang.String,net.sf.saxon.om.NodeInfo) throws java.lang.Exception}: Exception in extension function net.sf.saxon.s9api.SaxonApiException: Error in call to extension function {public javax.xml.transform.Source org.opengis.cite.wfs20.nsg.TestNGController.doTestRun(org.w3c.dom.Document) throws java.lang.Exception}: Exception in extension function java.lang.ExceptionInInitializerError |
| NSG WMS 1.3 Profile 1.0 0.5 Beta | - | - |
| NSG WMTS 1.0 Profile 1.0 0.4 Beta | https://raw.githubusercontent.com/opengeospatial/ets-wmts10-nsg10/master/src/test/resources/org/opengeospatial/cite/wmts10/ets/core/NSGWMTSImplementation.xml | java.lang.NoClassDefFoundError: com/sun/jersey/core/util/FeaturesAndProperties |
| OGC API - Tiles 1.0 0.2 Beta |  |  |
| OGC CDB 1.0 1.1 Final | https://github.com/opengeospatial/ets-cdb10/blob/master/src/test/resources/CDB/20201115_Archive.zip | PASS |
| OGC EO Dataset Metadata GeoJSON 1.0 0.2 Beta | https://github.com/opengeospatial/ets-eo-geojson10/blob/main/src/test/resources/example-1-seasat.json https://github.com/opengeospatial/ets-eo-geojson10/blob/main/src/test/resources/example-1-seasat-collection.json | Error in call to extension function {public java.lang.Object com.occamlab.te.TECore.callFunction(net.sf.saxon.expr.XPathContext,java.lang.String,java.lang.String,net.sf.saxon.om.NodeInfo) throws java.lang.Exception}: Exception in extension function net.sf.saxon.s9api.SaxonApiException: Error in call to extension function {public javax.xml.transform.Source org.opengis.cite.eogeojson10.TestNGController.doTestRun(org.w3c.dom.Document) throws java.lang.Exception}: Exception in extension function java.lang.NoClassDefFoundError: com/sun/jersey/core/util/FeaturesAndProperties |
| OGC GeoRSS Encoding Standard 1.0 1.0 Final | https://github.com/opengeospatial/ets-georss10/blob/master/src/test/resources/point_georss.xml | Error in call to extension function {public java.lang.Object com.occamlab.te.TECore.callFunction(net.sf.saxon.expr.XPathContext,java.lang.String,java.lang.String,net.sf.saxon.om.NodeInfo) throws java.lang.Exception}: Exception in extension function net.sf.saxon.s9api.SaxonApiException: Error in call to extension function {public javax.xml.transform.Source org.opengis.cite.georss10.TestNGController.doTestRun(org.w3c.dom.Document) throws java.lang.Exception}: Exception in extension function java.lang.NoClassDefFoundError: com/sun/jersey/core/util/FeaturesAndProperties |
| OGC KML 2.2 1.15 Final | https://raw.githubusercontent.com/opengeospatial/ets-kml22/master/src/test/resources/kml/KML_Samples.kml | Error in call to extension function {public java.lang.Object com.occamlab.te.TECore.callFunction(net.sf.saxon.expr.XPathContext,java.lang.String,java.lang.String,net.sf.saxon.om.NodeInfo) throws java.lang.Exception}: Exception in extension function net.sf.saxon.s9api.SaxonApiException: Error in call to extension function {public javax.xml.transform.Source org.opengis.cite.kml22.TestNGController.doTestRun(org.w3c.dom.Document) throws java.lang.Exception}: Exception in extension function java.lang.NoClassDefFoundError: com/sun/jersey/spi/inject/Errors$Closure |
| OGC KML 2.x 2.x 0.5 Beta | https://raw.githubusercontent.com/opengeospatial/ets-kml2/master/src/test/resources/kml22/Placemark-001.xml | Error in call to extension function {public java.lang.Object com.occamlab.te.TECore.callFunction(net.sf.saxon.expr.XPathContext,java.lang.String,java.lang.String,net.sf.saxon.om.NodeInfo) throws java.lang.Exception}: Exception in extension function net.sf.saxon.s9api.SaxonApiException: Error in call to extension function {public javax.xml.transform.Source org.opengis.cite.kml2.TestNGController.doTestRun(org.w3c.dom.Document) throws java.lang.Exception}: Exception in extension function java.lang.NoClassDefFoundError: com/sun/jersey/spi/inject/Errors$Closure |
| OGC Web Service Security Client 1.0 0.6 Beta |  |  |
| OWS Context 1.0 0.2 Beta | http://schemas.opengis.net/owc/1.0/examples/sea_ice_extent_01.atom | Error in call to extension function {public java.lang.Object com.occamlab.te.TECore.callFunction(net.sf.saxon.expr.XPathContext,java.lang.String,java.lang.String,net.sf.saxon.om.NodeInfo) throws java.lang.Exception}: Exception in extension function net.sf.saxon.s9api.SaxonApiException: Error in call to extension function {public javax.xml.transform.Source org.opengis.cite.owc10.TestNGController.doTestRun(org.w3c.dom.Document) throws java.lang.Exception}: Exception in extension function java.lang.NoClassDefFoundError: com/sun/jersey/spi/inject/Errors$Closure |
| Observations and Measurements - XML Implementation (OMXML) 2.0 1.1 Final |  http://www.w3schools.com/xml/note.xml | Error in call to extension function {public java.lang.Object com.occamlab.te.TECore.callFunction(net.sf.saxon.expr.XPathContext,java.lang.String,java.lang.String,net.sf.saxon.om.NodeInfo) throws java.lang.Exception}: Exception in extension function net.sf.saxon.s9api.SaxonApiException: Error in call to extension function {public javax.xml.transform.Source org.opengis.cite.om20.TestNGController.doTestRun(org.w3c.dom.Document) throws java.lang.Exception}: Exception in extension function java.lang.NoClassDefFoundError: com/sun/jersey/spi/inject/Errors$Closure |
| SWE Common Data Model Encoding Standard 2.0 1.1 Final | http://www.w3schools.com/xml/note.xml | Error in call to extension function {public java.lang.Object com.occamlab.te.TECore.callFunction(net.sf.saxon.expr.XPathContext,java.lang.String,java.lang.String,net.sf.saxon.om.NodeInfo) throws java.lang.Exception}: Exception in extension function net.sf.saxon.s9api.SaxonApiException: Error in call to extension function {public javax.xml.transform.Source org.opengis.cite.swecommon20.TestNGController.doTestRun(org.w3c.dom.Document) throws java.lang.Exception}: Exception in extension function java.lang.NoClassDefFoundError: com/sun/jersey/spi/inject/Errors$Closure |
| Sensor Model Language (SensorML) 1.0.1 1.0.1 Final | https://raw.githubusercontent.com/opengeospatial/ets-sensorml10/master/src/main/example/SensorML1.0.1.xml | PASS |
| Sensor Model Language (SensorML) 2.0 1.0 Final | https://raw.githubusercontent.com/opengeospatial/ets-sensorml20/master/src/test/resources/SimpleProcess.xml | Error in call to extension function {public java.lang.Object com.occamlab.te.TECore.callFunction(net.sf.saxon.expr.XPathContext,java.lang.String,java.lang.String,net.sf.saxon.om.NodeInfo) throws java.lang.Exception}: Exception in extension function net.sf.saxon.s9api.SaxonApiException: Error in call to extension function {public javax.xml.transform.Source org.opengis.cite.sensorml20.TestNGController.doTestRun(org.w3c.dom.Document) throws java.lang.Exception}: Exception in extension function java.lang.NoClassDefFoundError: com/sun/jersey/spi/inject/Errors$Closure |
| Sensor Observation Service (SOS) 1.0.0 1.14 Final |  |  |
| Sensor Observation Service (SOS) 2.0 1.14 Final |  |  |
| Sensor Planning Service (SPS) 2.0 1.11 Final | http://demo.pycsw.org/cite/csw?service=CSW&version=2.0.2&request=GetCapabilities | PASS |
| SensorThings API 1.0 1.4 Final |  |  |
| Simple Feature Access - SQL (SFS) 1.1 1.8 Final |  |  |
| Simple Feature Access - SQL (SFS) 1.2.1 1.4 Final |  |  |
| Web Coverage Service (WCS) 1.0.0 1.17 Final |  |  |
| Web Coverage Service (WCS) 1.1.1 1.17 Final |  |  |
| Web Coverage Service (WCS) 2.0.1 1.20 Final |  |  |
| Web Feature Service (WFS) 1.0.0 1.13 Final | stuck on 'Executing tests... |  |
| Web Feature Service (WFS) 1.1.0 1.36 Final | https://cite.deegree.org/deegree-webservices-3.5.6/services/wfs100?service=WFS&request=GetCapabilities | Executed successfully and show assertion failed |

**Comment by jiann** [comment]
Created issues for test suites:

- https://github.com/opengeospatial/ets-wfs20-dgiwg/issues/35
- https://github.com/opengeospatial/ets-gmljpx20/issues/46
- https://github.com/opengeospatial/ets-gmljpx20/issues/46
- https://github.com/opengeospatial/ets-gpkg10/issues/44
- https://github.com/opengeospatial/ets-gpkg12/issues/130
- https://github.com/opengeospatial/ets-geopose10/issues/20
- https://github.com/opengeospatial/ets-indoorgml10/issues/10
- https://github.com/opengeospatial/ets-wfs20-nsg10/issues/29
- https://github.com/opengeospatial/ets-wmts10-nsg10/issues/60
- https://github.com/opengeospatial/ets-eo-geojson10/issues/14
- https://github.com/opengeospatial/ets-georss10/issues/23
- https://github.com/opengeospatial/ets-kml22/issues/33
- https://github.com/opengeospatial/ets-kml2/issues/15
- https://github.com/opengeospatial/ets-omxml20/issues/31
- https://github.com/opengeospatial/ets-swecommon20/issues/28
- https://github.com/opengeospatial/ets-sensorml20/issues/62
